In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
#Text example
sentences = [
    "The quick brown fox jumps over the lazy dog.",
    "Machine learning is a fascinating field of study.",
    "Word embeddings help in capturing semantic meanings of words.",
    "I love exploring new ideas and concepts.",
    "The weather today is quite pleasant and sunny."
]

In [27]:
vocab_size = 10000 #len(sentences)

In [28]:
ohe_repr = [one_hot(words, vocab_size) for words in sentences]
ohe_repr

[[8649, 7887, 279, 3510, 6793, 2373, 8649, 4849, 5306],
 [3522, 5687, 7738, 9110, 8054, 7245, 8128, 9749],
 [8735, 1332, 3079, 3812, 3992, 1887, 5640, 8128, 9243],
 [3736, 3390, 9159, 6586, 7734, 7019, 9172],
 [8649, 2849, 2570, 7738, 7212, 1952, 7019, 1216]]

In [29]:
#importing libraries for word embeddings
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import  pad_sequences
from tensorflow.keras.layers import Embedding
import numpy as np

In [30]:
#finding maximum length of a sentence can be.
sent_len = max(len(sentences) for sentences in ohe_repr)
sent_len

9

In [31]:
#adding 0 to make all the arrays in same dimension
padded_form = pad_sequences(ohe_repr,padding='pre', maxlen=sent_len)
print(padded_form)


[[8649 7887  279 3510 6793 2373 8649 4849 5306]
 [   0 3522 5687 7738 9110 8054 7245 8128 9749]
 [8735 1332 3079 3812 3992 1887 5640 8128 9243]
 [   0    0 3736 3390 9159 6586 7734 7019 9172]
 [   0 8649 2849 2570 7738 7212 1952 7019 1216]]


In [32]:
#adding embedding to each word and train accordingly
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=10, input_length=sent_len))


In [33]:
#train
model.compile('adam','mse')

In [36]:
#prediction
model.predict(padded_form)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step


array([[[-1.21726282e-02,  4.60361280e-02, -4.83429320e-02,
         -3.71954218e-02,  2.54346393e-02, -1.10672712e-02,
          3.07111405e-02, -4.13973257e-03,  1.31161921e-02,
         -3.63805294e-02],
        [ 1.82967074e-02,  4.02966850e-02,  1.93487071e-02,
         -4.73260880e-03, -3.18573341e-02,  3.31545211e-02,
          3.42277028e-02, -2.22085956e-02, -3.99763584e-02,
          1.55419596e-02],
        [-1.21762380e-02, -1.04770176e-02, -3.36851478e-02,
          3.08974721e-02,  3.48751433e-02,  1.13661401e-02,
          3.71027030e-02,  5.54471090e-03, -2.53184326e-02,
         -1.02221966e-02],
        [ 3.53655107e-02, -4.63812128e-02,  4.63130586e-02,
         -2.77674682e-02, -3.47349532e-02, -2.29525454e-02,
          2.72057950e-04,  4.05301712e-02, -3.03184986e-02,
          2.14559957e-03],
        [-1.06398091e-02,  1.29573420e-03,  2.52759494e-02,
         -1.50832646e-02, -1.96508896e-02, -3.91255245e-02,
         -1.99814569e-02, -1.90889835e-03,  4.649840

In [1]:
#implementing through transformers

In [ ]:
from sentence_transformers import SentenceTransformer

#Example sentences
sentences = [
    "The quick brown fox jumps over the lazy dog.",
    "Machine learning is a fascinating field of study.",
    "Word embeddings help in capturing semantic meanings of words.",
    "I love exploring new ideas and concepts.",
    "The weather today is quite pleasant and sunny."
]

#Load a pre-trained model for embeddings
model = SentenceTransformer('all-MiniLM-L6-v2')

#Generate embeddings
embeddings = model.encode(sentences)

# Display the embeddings
for i, sentence in enumerate(sentences):
    print(f"Sentence: {sentence}")
    print(f"Embedding: {embeddings[i][:5]}...")  #Display first 5 dimensions for brevity
    print()
